function [y2, np] = z2qs(A, c_double, s, type_pol)
%
%--------------------------------------------------------------------------
% Description
%--------------------------------------------------------------------------
% It evaluates the matrix polynomial P(A) using the coefficient structure 
% generated by function MatrixPolEval2. It also returns the total number of
% matrix products performed.
%
% [y2, np] = z2qs(A, c_double, s, type_pol)
%
% This function implements formulas (10)–(14) and (23) from [1],
% corresponding to a combined 6s–Paterson–Stockmeyer (PS) stable evaluation
% scheme of matrix polynomials with two-product savings. For that, it
%   1) Precompute powers A^0, A^1, ..., A^s.
%   2) Evaluate the 6s core using a 4s internal variant.
%   3) Combine the result with the PS residual.
% The funtion reduces the total number of matrix multiplications compared 
% with classical PS evaluation.
%
% See also MatrixPolEval2.
%
%--------------------------------------------------------------------------
% Input arguments
%--------------------------------------------------------------------------
% - A: square matrix of size n-by-n.
% - c_double: coefficient vector of the combined 6s–PS scheme [1]. It must 
%   be ordered as:
%   c_double = [c(1)...c(q) | c(q+1)...c(m+1)]
%   where:
%   * c(1)...c(q) correspond to the PS part.
%   * c(q+1)...c(m+1) correspond to the 6s formulation.
%   The polynomial degree is m, where m = q + 6s. Coefficients may be 
%   stored in vpa, double, or single precision.
% - s: Parameter s of the 6s formulation, satisfying m − 6s ≥ 0. Typically 
%   chosen to minimize computational cost.
% - type_pol: variant of the 4s formulation used inside the 6s scheme.
%   Possible values:
%   1  → Formula (11) in [1]
%   2  → Formula (12) in [1]
%   3  → Formula (13) in [1]
%   The recommended choice is the variant yielding the smallest forward 
%   error according to the  stability test in [3, Ex. 3.1].
%
%--------------------------------------------------------------------------
% Output arguments
%--------------------------------------------------------------------------
% - y2: matrix polynomial evaluated at A.
% - np: total number of matrix products performed:
%   np = s + 2 + ceil(q/s), where q = m − 6s.
%
%--------------------------------------------------------------------------
% Copyright
%--------------------------------------------------------------------------
% Authors: Javier Ibáñez, Jorge Sastre and José Miguel Alonso
% Revised version: August 3, 2026.
%
% High Performance Scientific Computing Group (HiPerSC)
% Universitat Politècnica de València (Spain)
%
%--------------------------------------------------------------------------
% References
%--------------------------------------------------------------------------
% [1] J. Ibáñez, J. Sastre, J.M. Alonso, E. Defez, A MATLAB Tool for the 
%     Stable Generation of Matrix Polynomial Evaluation Schemes with 
%     Two-Product Savings, arXiv:2607.28286, 2026. 
%     https://arxiv.org/abs/2607.28286
% [2] J. Sastre, J. Ibáñez, Efficient Evaluation of Matrix Polynomials 
%     Beyond the Paterson-Stockmeyer Method, Mathematics 9(14), 1600, 2021,
%     https://doi.org/10.3390/math9141600
% [3] J. Sastre, Efficient evaluation of matrix polynomials, Linear 
%     Algebra Applications, 539, 2018, 229-250.
%     https://doi.org/10.1016/j.laa.2017.11.010
%

% Matrix size
n = length(A);

% Degree of the polynomial
m = length(c_double) - 1;

% Number of coefficients used in the Paterson–Stockmeyer part
q = m - 6*s;

% Extract PS coefficients if present
if q > 0
    p = c_double(1:q);
end

% Extract 6s-formulation coefficients
c = c_double(q+1:m+1);

% ------------------------------------------------------------
% Precompute powers of A: I, A, A^2, ..., A^s
% ------------------------------------------------------------
pA = cell(s+1,1);
pA{1} = eye(n);     % A^0
pA{2} = A;          % A^1
for i = 3:s+1
    pA{i} = pA{i-1} * A;  % A^i
end

% ------------------------------------------------------------
% First block: compute y0
% ------------------------------------------------------------
y0 = c(5*s+2) * pA{2};
for i = 3:s+1
    y0 = y0 + c(5*s+i) * pA{i};
end
y0 = y0 * pA{s+1};

% ------------------------------------------------------------
% Compute y1 depending on the selected 4s variant
% ------------------------------------------------------------
if type_pol == 1
    
    y1 = y0;
    for i = 2:s+1
        y1 = y1 + c(4*s+i) * pA{i};
    end
    
    y1m = y0;
    for i = 3:s+1
        y1m = y1m + c(3*s+i) * pA{i};
    end
    
    y1 = y1 * y1m;
    y1 = y1 + c(3*s+2) * y0;
    
    for i = 2:s+1
        y1 = y1 + c(2*s+i) * pA{i};
    end
    
elseif type_pol == 2
    
    y1 = y0 + c(4*s+1) * pA{1};
    for i = 2:s+1
        y1 = y1 + c(4*s+i) * pA{i};
    end
    
    y1m = y0;
    for i = 3:s+1
        y1m = y1m + c(3*s+i-1) * pA{i};
    end
    
    y1 = y1 * y1m;
    
    for i = 2:s+1
        y1 = y1 + c(2*s+i) * pA{i};
    end
    
else
    
    y1 = y0;
    for i = 2:s+1
        y1 = y1 + c(4*s+i) * pA{i};
    end
    
    y1m = y0;
    for i = 2:s+1
        y1m = y1m + c(3*s+i) * pA{i};
    end
    
    y1 = y1 * y1m;
    
    for i = 2:s+1
        y1 = y1 + c(2*s+i) * pA{i};
    end
end

% ------------------------------------------------------------
% Final combination for the 6s formulation
% ------------------------------------------------------------
y2 = y0;
for i = 2:s+1
    y2 = y2 + c(s+i) * pA{i};
end

y2 = y1 * y2 + c(1) * pA{1};

for i = 2:s+1
    y2 = y2 + c(i) * pA{i};
end

% ------------------------------------------------------------
% Paterson–Stockmeyer evaluation of the remaining part
% ------------------------------------------------------------
t = floor(q/s);
r = mod(q, s);

for k = 0:t-1
    y2 = pA{s+1} * y2;
    for i = 0:s-1
        y2 = y2 + p(q - k*s - i) * pA{s-i};
    end
end

y2 = y2 * pA{r+1};
for i = 1:r
    y2 = y2 + p(i) * pA{i};
end

% Total number of matrix products
np = s + 2 + ceil(q/s);

end